/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface Crop {
  'id' : bigint,
  'name' : string,
  'cropType' : string,
  'plotName' : string,
}
export interface Date { 'day' : bigint, 'month' : bigint, 'year' : bigint }
export interface FertilizerSchedule {
  'id' : bigint,
  'fertilizerName' : string,
  'scheduledDate' : Date,
  'isDone' : boolean,
  'cropId' : bigint,
  'notes' : string,
}
export interface SpraySchedule {
  'id' : bigint,
  'scheduledDate' : Date,
  'isDone' : boolean,
  'cropId' : bigint,
  'notes' : string,
  'sprayName' : string,
}
export interface UserProfile { 'name' : string }
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface _SERVICE {
  '_initializeAccessControlWithSecret' : ActorMethod<[string], undefined>,
  'addCrop' : ActorMethod<[string, string, string], bigint>,
  'addFertilizerSchedule' : ActorMethod<[bigint, string, Date, string], bigint>,
  'addSpraySchedule' : ActorMethod<[bigint, string, Date, string], bigint>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'deleteCrop' : ActorMethod<[bigint], undefined>,
  'getCallerUserProfile' : ActorMethod<[], [] | [UserProfile]>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getFertilizerSchedulesForMonth' : ActorMethod<
    [bigint, bigint],
    Array<FertilizerSchedule>
  >,
  'getSpraySchedulesForMonth' : ActorMethod<
    [bigint, bigint],
    Array<SpraySchedule>
  >,
  'getTodaysFertilizerSchedules' : ActorMethod<
    [Date],
    Array<FertilizerSchedule>
  >,
  'getTodaysSpraySchedules' : ActorMethod<[Date], Array<SpraySchedule>>,
  'getUserProfile' : ActorMethod<[Principal], [] | [UserProfile]>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'listCrops' : ActorMethod<[], Array<Crop>>,
  'markFertilizerScheduleAsDone' : ActorMethod<[bigint], undefined>,
  'markSprayScheduleAsDone' : ActorMethod<[bigint], undefined>,
  'saveCallerUserProfile' : ActorMethod<[UserProfile], undefined>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];