/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const Date = IDL.Record({
  'day' : IDL.Nat,
  'month' : IDL.Nat,
  'year' : IDL.Nat,
});
export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const UserProfile = IDL.Record({ 'name' : IDL.Text });
export const FertilizerSchedule = IDL.Record({
  'id' : IDL.Nat,
  'fertilizerName' : IDL.Text,
  'scheduledDate' : Date,
  'isDone' : IDL.Bool,
  'cropId' : IDL.Nat,
  'notes' : IDL.Text,
});
export const SpraySchedule = IDL.Record({
  'id' : IDL.Nat,
  'scheduledDate' : Date,
  'isDone' : IDL.Bool,
  'cropId' : IDL.Nat,
  'notes' : IDL.Text,
  'sprayName' : IDL.Text,
});
export const Crop = IDL.Record({
  'id' : IDL.Nat,
  'name' : IDL.Text,
  'cropType' : IDL.Text,
  'plotName' : IDL.Text,
});

export const idlService = IDL.Service({
  '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
  'addCrop' : IDL.Func([IDL.Text, IDL.Text, IDL.Text], [IDL.Nat], []),
  'addFertilizerSchedule' : IDL.Func(
      [IDL.Nat, IDL.Text, Date, IDL.Text],
      [IDL.Nat],
      [],
    ),
  'addSpraySchedule' : IDL.Func(
      [IDL.Nat, IDL.Text, Date, IDL.Text],
      [IDL.Nat],
      [],
    ),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'deleteCrop' : IDL.Func([IDL.Nat], [], []),
  'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getFertilizerSchedulesForMonth' : IDL.Func(
      [IDL.Nat, IDL.Nat],
      [IDL.Vec(FertilizerSchedule)],
      ['query'],
    ),
  'getSpraySchedulesForMonth' : IDL.Func(
      [IDL.Nat, IDL.Nat],
      [IDL.Vec(SpraySchedule)],
      ['query'],
    ),
  'getTodaysFertilizerSchedules' : IDL.Func(
      [Date],
      [IDL.Vec(FertilizerSchedule)],
      ['query'],
    ),
  'getTodaysSpraySchedules' : IDL.Func(
      [Date],
      [IDL.Vec(SpraySchedule)],
      ['query'],
    ),
  'getUserProfile' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(UserProfile)],
      ['query'],
    ),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'listCrops' : IDL.Func([], [IDL.Vec(Crop)], ['query']),
  'markFertilizerScheduleAsDone' : IDL.Func([IDL.Nat], [], []),
  'markSprayScheduleAsDone' : IDL.Func([IDL.Nat], [], []),
  'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const Date = IDL.Record({
    'day' : IDL.Nat,
    'month' : IDL.Nat,
    'year' : IDL.Nat,
  });
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const UserProfile = IDL.Record({ 'name' : IDL.Text });
  const FertilizerSchedule = IDL.Record({
    'id' : IDL.Nat,
    'fertilizerName' : IDL.Text,
    'scheduledDate' : Date,
    'isDone' : IDL.Bool,
    'cropId' : IDL.Nat,
    'notes' : IDL.Text,
  });
  const SpraySchedule = IDL.Record({
    'id' : IDL.Nat,
    'scheduledDate' : Date,
    'isDone' : IDL.Bool,
    'cropId' : IDL.Nat,
    'notes' : IDL.Text,
    'sprayName' : IDL.Text,
  });
  const Crop = IDL.Record({
    'id' : IDL.Nat,
    'name' : IDL.Text,
    'cropType' : IDL.Text,
    'plotName' : IDL.Text,
  });
  
  return IDL.Service({
    '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
    'addCrop' : IDL.Func([IDL.Text, IDL.Text, IDL.Text], [IDL.Nat], []),
    'addFertilizerSchedule' : IDL.Func(
        [IDL.Nat, IDL.Text, Date, IDL.Text],
        [IDL.Nat],
        [],
      ),
    'addSpraySchedule' : IDL.Func(
        [IDL.Nat, IDL.Text, Date, IDL.Text],
        [IDL.Nat],
        [],
      ),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'deleteCrop' : IDL.Func([IDL.Nat], [], []),
    'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getFertilizerSchedulesForMonth' : IDL.Func(
        [IDL.Nat, IDL.Nat],
        [IDL.Vec(FertilizerSchedule)],
        ['query'],
      ),
    'getSpraySchedulesForMonth' : IDL.Func(
        [IDL.Nat, IDL.Nat],
        [IDL.Vec(SpraySchedule)],
        ['query'],
      ),
    'getTodaysFertilizerSchedules' : IDL.Func(
        [Date],
        [IDL.Vec(FertilizerSchedule)],
        ['query'],
      ),
    'getTodaysSpraySchedules' : IDL.Func(
        [Date],
        [IDL.Vec(SpraySchedule)],
        ['query'],
      ),
    'getUserProfile' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(UserProfile)],
        ['query'],
      ),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'listCrops' : IDL.Func([], [IDL.Vec(Crop)], ['query']),
    'markFertilizerScheduleAsDone' : IDL.Func([IDL.Nat], [], []),
    'markSprayScheduleAsDone' : IDL.Func([IDL.Nat], [], []),
    'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
  });
};

export const init = ({ IDL }) => { return []; };