/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Actor, HttpAgent, type HttpAgentOptions, type ActorConfig, type Agent, type ActorSubclass } from "@icp-sdk/core/agent";
import type { Principal } from "@icp-sdk/core/principal";
import { idlFactory, type _SERVICE } from "./declarations/backend.did";
export interface Some<T> {
    __kind__: "Some";
    value: T;
}
export interface None {
    __kind__: "None";
}
export type Option<T> = Some<T> | None;
function some<T>(value: T): Some<T> {
    return {
        __kind__: "Some",
        value: value
    };
}
function none(): None {
    return {
        __kind__: "None"
    };
}
function isNone<T>(option: Option<T>): option is None {
    return option.__kind__ === "None";
}
function isSome<T>(option: Option<T>): option is Some<T> {
    return option.__kind__ === "Some";
}
function unwrap<T>(option: Option<T>): T {
    if (isNone(option)) {
        throw new Error("unwrap: none");
    }
    return option.value;
}
function candid_some<T>(value: T): [T] {
    return [
        value
    ];
}
function candid_none<T>(): [] {
    return [];
}
function record_opt_to_undefined<T>(arg: T | null): T | undefined {
    return arg == null ? undefined : arg;
}
export class ExternalBlob {
    _blob?: Uint8Array<ArrayBuffer> | null;
    directURL: string;
    onProgress?: (percentage: number) => void = undefined;
    private constructor(directURL: string, blob: Uint8Array<ArrayBuffer> | null){
        if (blob) {
            this._blob = blob;
        }
        this.directURL = directURL;
    }
    static fromURL(url: string): ExternalBlob {
        return new ExternalBlob(url, null);
    }
    static fromBytes(blob: Uint8Array<ArrayBuffer>): ExternalBlob {
        const url = URL.createObjectURL(new Blob([
            new Uint8Array(blob)
        ], {
            type: 'application/octet-stream'
        }));
        return new ExternalBlob(url, blob);
    }
    public async getBytes(): Promise<Uint8Array<ArrayBuffer>> {
        if (this._blob) {
            return this._blob;
        }
        const response = await fetch(this.directURL);
        const blob = await response.blob();
        this._blob = new Uint8Array(await blob.arrayBuffer());
        return this._blob;
    }
    public getDirectURL(): string {
        return this.directURL;
    }
    public withUploadProgress(onProgress: (percentage: number) => void): ExternalBlob {
        this.onProgress = onProgress;
        return this;
    }
}
export interface SpraySchedule {
    id: bigint;
    scheduledDate: Date_;
    isDone: boolean;
    cropId: bigint;
    notes: string;
    sprayName: string;
}
export interface Crop {
    id: bigint;
    name: string;
    cropType: string;
    plotName: string;
}
export interface Date_ {
    day: bigint;
    month: bigint;
    year: bigint;
}
export interface FertilizerSchedule {
    id: bigint;
    fertilizerName: string;
    scheduledDate: Date_;
    isDone: boolean;
    cropId: bigint;
    notes: string;
}
export interface UserProfile {
    name: string;
}
export enum UserRole {
    admin = "admin",
    user = "user",
    guest = "guest"
}
export interface backendInterface {
    _initializeAccessControlWithSecret(userSecret: string): Promise<void>;
    addCrop(name: string, cropType: string, plotName: string): Promise<bigint>;
    addFertilizerSchedule(cropId: bigint, fertilizerName: string, scheduledDate: Date_, notes: string): Promise<bigint>;
    addSpraySchedule(cropId: bigint, sprayName: string, scheduledDate: Date_, notes: string): Promise<bigint>;
    assignCallerUserRole(user: Principal, role: UserRole): Promise<void>;
    deleteCrop(cropId: bigint): Promise<void>;
    deleteFertilizerSchedule(scheduleId: bigint): Promise<void>;
    deleteSpraySchedule(scheduleId: bigint): Promise<void>;
    getAllFertilizerSchedules(): Promise<Array<FertilizerSchedule>>;
    getAllSpraySchedules(): Promise<Array<SpraySchedule>>;
    getCallerUserProfile(): Promise<UserProfile | null>;
    getCallerUserRole(): Promise<UserRole>;
    getFertilizerSchedulesForMonth(month: bigint, year: bigint): Promise<Array<FertilizerSchedule>>;
    getSpraySchedulesForMonth(month: bigint, year: bigint): Promise<Array<SpraySchedule>>;
    getTodaysFertilizerSchedules(today: Date_): Promise<Array<FertilizerSchedule>>;
    getTodaysSpraySchedules(today: Date_): Promise<Array<SpraySchedule>>;
    getUserProfile(user: Principal): Promise<UserProfile | null>;
    isCallerAdmin(): Promise<boolean>;
    listCrops(): Promise<Array<Crop>>;
    markFertilizerScheduleAsDone(scheduleId: bigint): Promise<void>;
    markSprayScheduleAsDone(scheduleId: bigint): Promise<void>;
    saveCallerUserProfile(profile: UserProfile): Promise<void>;
    updateCrop(cropId: bigint, name: string, cropType: string, plotName: string): Promise<void>;
    updateFertilizerSchedule(scheduleId: bigint, fertilizerName: string, scheduledDate: Date_, notes: string): Promise<void>;
    updateSpraySchedule(scheduleId: bigint, sprayName: string, scheduledDate: Date_, notes: string): Promise<void>;
}
import type { UserProfile as _UserProfile, UserRole as _UserRole } from "./declarations/backend.did.d.ts";
export class Backend implements backendInterface {
    constructor(private actor: ActorSubclass<_SERVICE>, private _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, private _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, private processError?: (error: unknown) => never){}
    async _initializeAccessControlWithSecret(arg0: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor._initializeAccessControlWithSecret(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._initializeAccessControlWithSecret(arg0);
            return result;
        }
    }
    async addCrop(arg0: string, arg1: string, arg2: string): Promise<bigint> {
        if (this.processError) {
            try {
                const result = await this.actor.addCrop(arg0, arg1, arg2);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addCrop(arg0, arg1, arg2);
            return result;
        }
    }
    async addFertilizerSchedule(arg0: bigint, arg1: string, arg2: Date_, arg3: string): Promise<bigint> {
        if (this.processError) {
            try {
                const result = await this.actor.addFertilizerSchedule(arg0, arg1, arg2, arg3);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addFertilizerSchedule(arg0, arg1, arg2, arg3);
            return result;
        }
    }
    async addSpraySchedule(arg0: bigint, arg1: string, arg2: Date_, arg3: string): Promise<bigint> {
        if (this.processError) {
            try {
                const result = await this.actor.addSpraySchedule(arg0, arg1, arg2, arg3);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addSpraySchedule(arg0, arg1, arg2, arg3);
            return result;
        }
    }
    async assignCallerUserRole(arg0: Principal, arg1: UserRole): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.assignCallerUserRole(arg0, to_candid_UserRole_n1(this._uploadFile, this._downloadFile, arg1));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.assignCallerUserRole(arg0, to_candid_UserRole_n1(this._uploadFile, this._downloadFile, arg1));
            return result;
        }
    }
    async deleteCrop(arg0: bigint): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteCrop(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteCrop(arg0);
            return result;
        }
    }
    async deleteFertilizerSchedule(arg0: bigint): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteFertilizerSchedule(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteFertilizerSchedule(arg0);
            return result;
        }
    }
    async deleteSpraySchedule(arg0: bigint): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteSpraySchedule(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteSpraySchedule(arg0);
            return result;
        }
    }
    async getAllFertilizerSchedules(): Promise<Array<FertilizerSchedule>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllFertilizerSchedules();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllFertilizerSchedules();
            return result;
        }
    }
    async getAllSpraySchedules(): Promise<Array<SpraySchedule>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllSpraySchedules();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllSpraySchedules();
            return result;
        }
    }
    async getCallerUserProfile(): Promise<UserProfile | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getCallerUserProfile();
                return from_candid_opt_n3(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCallerUserProfile();
            return from_candid_opt_n3(this._uploadFile, this._downloadFile, result);
        }
    }
    async getCallerUserRole(): Promise<UserRole> {
        if (this.processError) {
            try {
                const result = await this.actor.getCallerUserRole();
                return from_candid_UserRole_n4(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCallerUserRole();
            return from_candid_UserRole_n4(this._uploadFile, this._downloadFile, result);
        }
    }
    async getFertilizerSchedulesForMonth(arg0: bigint, arg1: bigint): Promise<Array<FertilizerSchedule>> {
        if (this.processError) {
            try {
                const result = await this.actor.getFertilizerSchedulesForMonth(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getFertilizerSchedulesForMonth(arg0, arg1);
            return result;
        }
    }
    async getSpraySchedulesForMonth(arg0: bigint, arg1: bigint): Promise<Array<SpraySchedule>> {
        if (this.processError) {
            try {
                const result = await this.actor.getSpraySchedulesForMonth(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getSpraySchedulesForMonth(arg0, arg1);
            return result;
        }
    }
    async getTodaysFertilizerSchedules(arg0: Date_): Promise<Array<FertilizerSchedule>> {
        if (this.processError) {
            try {
                const result = await this.actor.getTodaysFertilizerSchedules(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getTodaysFertilizerSchedules(arg0);
            return result;
        }
    }
    async getTodaysSpraySchedules(arg0: Date_): Promise<Array<SpraySchedule>> {
        if (this.processError) {
            try {
                const result = await this.actor.getTodaysSpraySchedules(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getTodaysSpraySchedules(arg0);
            return result;
        }
    }
    async getUserProfile(arg0: Principal): Promise<UserProfile | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getUserProfile(arg0);
                return from_candid_opt_n3(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getUserProfile(arg0);
            return from_candid_opt_n3(this._uploadFile, this._downloadFile, result);
        }
    }
    async isCallerAdmin(): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.isCallerAdmin();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.isCallerAdmin();
            return result;
        }
    }
    async listCrops(): Promise<Array<Crop>> {
        if (this.processError) {
            try {
                const result = await this.actor.listCrops();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.listCrops();
            return result;
        }
    }
    async markFertilizerScheduleAsDone(arg0: bigint): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.markFertilizerScheduleAsDone(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.markFertilizerScheduleAsDone(arg0);
            return result;
        }
    }
    async markSprayScheduleAsDone(arg0: bigint): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.markSprayScheduleAsDone(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.markSprayScheduleAsDone(arg0);
            return result;
        }
    }
    async saveCallerUserProfile(arg0: UserProfile): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.saveCallerUserProfile(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.saveCallerUserProfile(arg0);
            return result;
        }
    }
    async updateCrop(arg0: bigint, arg1: string, arg2: string, arg3: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updateCrop(arg0, arg1, arg2, arg3);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateCrop(arg0, arg1, arg2, arg3);
            return result;
        }
    }
    async updateFertilizerSchedule(arg0: bigint, arg1: string, arg2: Date_, arg3: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updateFertilizerSchedule(arg0, arg1, arg2, arg3);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateFertilizerSchedule(arg0, arg1, arg2, arg3);
            return result;
        }
    }
    async updateSpraySchedule(arg0: bigint, arg1: string, arg2: Date_, arg3: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updateSpraySchedule(arg0, arg1, arg2, arg3);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateSpraySchedule(arg0, arg1, arg2, arg3);
            return result;
        }
    }
    async getPlotSchedulesPublic(arg0, arg1) {
        if (this.processError) {
            try { return await this.actor.getPlotSchedulesPublic(arg0, arg1); } catch (e) { this.processError(e); throw new Error("unreachable"); }
        } else { return await this.actor.getPlotSchedulesPublic(arg0, arg1); }
    }
    async createSharedPlot(arg0, arg1) {
        if (this.processError) {
            try { return await this.actor.createSharedPlot(arg0, arg1); } catch (e) { this.processError(e); throw new Error("unreachable"); }
        } else { return await this.actor.createSharedPlot(arg0, arg1); }
    }
    async inviteCollaborator(arg0, arg1) {
        if (this.processError) {
            try { await this.actor.inviteCollaborator(arg0, arg1); } catch (e) { this.processError(e); throw new Error("unreachable"); }
        } else { await this.actor.inviteCollaborator(arg0, arg1); }
    }
    async removeCollaborator(arg0, arg1) {
        if (this.processError) {
            try { await this.actor.removeCollaborator(arg0, arg1); } catch (e) { this.processError(e); throw new Error("unreachable"); }
        } else { await this.actor.removeCollaborator(arg0, arg1); }
    }
    async getMySharedPlots() {
        if (this.processError) {
            try { return await this.actor.getMySharedPlots(); } catch (e) { this.processError(e); throw new Error("unreachable"); }
        } else { return await this.actor.getMySharedPlots(); }
    }
    async addSharedFertilizerSchedule(arg0, arg1, arg2, arg3, arg4) {
        if (this.processError) {
            try { return await this.actor.addSharedFertilizerSchedule(arg0, arg1, arg2, arg3, arg4); } catch (e) { this.processError(e); throw new Error("unreachable"); }
        } else { return await this.actor.addSharedFertilizerSchedule(arg0, arg1, arg2, arg3, arg4); }
    }
    async deleteSharedFertilizerSchedule(arg0, arg1) {
        if (this.processError) {
            try { await this.actor.deleteSharedFertilizerSchedule(arg0, arg1); } catch (e) { this.processError(e); throw new Error("unreachable"); }
        } else { await this.actor.deleteSharedFertilizerSchedule(arg0, arg1); }
    }
    async addSharedSpraySchedule(arg0, arg1, arg2, arg3, arg4) {
        if (this.processError) {
            try { return await this.actor.addSharedSpraySchedule(arg0, arg1, arg2, arg3, arg4); } catch (e) { this.processError(e); throw new Error("unreachable"); }
        } else { return await this.actor.addSharedSpraySchedule(arg0, arg1, arg2, arg3, arg4); }
    }
    async deleteSharedSpraySchedule(arg0, arg1) {
        if (this.processError) {
            try { await this.actor.deleteSharedSpraySchedule(arg0, arg1); } catch (e) { this.processError(e); throw new Error("unreachable"); }
        } else { await this.actor.deleteSharedSpraySchedule(arg0, arg1); }
    }
    async getSharedPlotSchedules(arg0) {
        if (this.processError) {
            try { return await this.actor.getSharedPlotSchedules(arg0); } catch (e) { this.processError(e); throw new Error("unreachable"); }
        } else { return await this.actor.getSharedPlotSchedules(arg0); }
    }
    async deleteSharedPlot(arg0) {
        if (this.processError) {
            try { return await this.actor.deleteSharedPlot(arg0); } catch (e) { this.processError(e); throw new Error("unreachable"); }
        } else { return await this.actor.deleteSharedPlot(arg0); }
    }
    async renameSharedPlot(arg0, arg1, arg2) {
        if (this.processError) {
            try { return await this.actor.renameSharedPlot(arg0, arg1, arg2); } catch (e) { this.processError(e); throw new Error("unreachable"); }
        } else { return await this.actor.renameSharedPlot(arg0, arg1, arg2); }
    }

}
function from_candid_UserRole_n4(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _UserRole): UserRole {
    return from_candid_variant_n5(_uploadFile, _downloadFile, value);
}
function from_candid_opt_n3(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_UserProfile]): UserProfile | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_variant_n5(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    admin: null;
} | {
    user: null;
} | {
    guest: null;
}): UserRole {
    return "admin" in value ? UserRole.admin : "user" in value ? UserRole.user : "guest" in value ? UserRole.guest : value;
}
function to_candid_UserRole_n1(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserRole): _UserRole {
    return to_candid_variant_n2(_uploadFile, _downloadFile, value);
}
function to_candid_variant_n2(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserRole): {
    admin: null;
} | {
    user: null;
} | {
    guest: null;
} {
    return value == UserRole.admin ? {
        admin: null
    } : value == UserRole.user ? {
        user: null
    } : value == UserRole.guest ? {
        guest: null
    } : value;
}
export interface CreateActorOptions {
    agent?: Agent;
    agentOptions?: HttpAgentOptions;
    actorOptions?: ActorConfig;
    processError?: (error: unknown) => never;
}
export function createActor(canisterId: string, _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, options: CreateActorOptions = {}): Backend {
    const agent = options.agent || HttpAgent.createSync({
        ...options.agentOptions
    });
    if (options.agent && options.agentOptions) {
        console.warn("Detected both agent and agentOptions passed to createActor. Ignoring agentOptions and proceeding with the provided agent.");
    }
    const actor = Actor.createActor<_SERVICE>(idlFactory, {
        agent,
        canisterId: canisterId,
        ...options.actorOptions
    });
    return new Backend(actor, _uploadFile, _downloadFile, options.processError);
}
